### ISSUE TITLE
Test Ticket

### ISSUE THREAD

**Issue by valentinajemuovic** [alptium/katarina.ristanovic#1]
Hi @KatarinaR,

Please do the following:

1. Write a comment below that you have received this test ticket.
2. Please tag me using @ then typing my GitHub name.
3. Then close this ticket.

Thanks,
Valentina

**Comment by KatarinaR** [comment]
Hello
@valentinacupac

**Comment by KatarinaR** [comment]
@valentinacupac
I have done  task
