### ISSUE TITLE
Hello World

### ISSUE THREAD

**Issue by KatarinaR** [alptium/katarina.ristanovic#2]
@valentinacupac

I have done task

**Comment by valentinajemuovic** [comment]
@KatarinaR:
1. See https://github.com/alptium/valentina.cupac/wiki/03.-Hello-World comment 11.
2. There are duplicate projects appearing, hello-world and helloworld. Should be just one, see https://github.com/alptium/valentina.cupac/wiki/03.-Hello-World comment 2 regarding naming conventions choice.
3. Assignee is missing on this ticket.
4. Name of this task should be Hello World (as per the name I put in the tasks)

**Comment by valentinajemuovic** [comment]
@KatarinaR:
1. Not fixed.
2. Not fixed.
3. Ok.
4. Ok.

**Comment by KatarinaR** [comment]
@valentinacupac
2. Not fixed. ---- I don't know how to delete duplicate file Please help!!!

**Comment by valentinajemuovic** [comment]
@KatarinaR, delete it from Eclipse and delete it from disk. Then open up GitHub, it will register the deletion., and then you commit and push that. You can try it, and if it still doesn't work, we can try screen share.

**Comment by valentinajemuovic** [comment]
@KatarinaR, correct.
